(async () => {
  "use strict";
  const app = globalThis.__VOSS_SCROLL__;
  const fixture = document.querySelector("#fixture");
  const results = document.querySelector("#results");
  const log = [];
  let passed = 0;
  let failed = 0;
  const wait = (ms = 450) => new Promise(resolve => setTimeout(resolve, ms));
  const panelText = () => document.querySelector("#voss-scroll-panel")?.innerText || "";
  function check(name, predicate) {
    const ok = typeof predicate === "function" ? predicate() : predicate;
    if (ok) passed++; else failed++;
    log.push(`${ok ? "PASS" : "FAIL"}  ${name}`);
    results.textContent = `${passed} passed · ${failed} failed\n${log.join("\n")}`;
  }
  function note(id, title, extra = "") {
    return `<div class="note-container ${extra}" data-note-id="${id}"><div class="author-container"><a class="username" href="https://www.xiaohongshu.com/user/profile/testauthor">作者小林</a></div><h2 id="detail-title">${title}</h2><div id="detail-desc">这是当前笔记的正文 #日常</div><a href="https://www.xiaohongshu.com/explore/${id}">详情</a></div>`;
  }
  function video(id, desc, extra = "") {
    return `<div data-e2e="feed-item" data-video-id="${id}" class="${extra}"><video></video><a data-e2e="video-author-name" href="https://www.douyin.com/user/author">视频作者</a><div data-e2e="video-desc">${desc}</div><a href="https://www.douyin.com/video/${id}">详情</a></div>`;
  }
  try {
    check("域名边界：两站裸域名及子域名匹配，伪造后缀不匹配", app.adapters.douyin.matches("douyin.com") && app.adapters.douyin.matches("www.douyin.com") && !app.adapters.douyin.matches("douyin.com.evil.test") && app.adapters.xiaohongshu.matches("xiaohongshu.com") && !app.adapters.xiaohongshu.matches("notxiaohongshu.com"));
    fixture.innerHTML = '<nav>关注 推荐 登录 消息</nav><section class="note-item">信息流卡片不应当作当前笔记</section>';
    let runtime = app.start(app.adapters.xiaohongshu);
    await wait();
    check("小红书列表页保持等待，不抓导航或卡片", !panelText().includes("信息流卡片") && !panelText().includes("关注 推荐 登录"));
    document.querySelector("#vs-refresh").click();
    await wait();
    check("空页面手动重读会结束等待状态", !panelText().includes("正在重新读取"));
    fixture.innerHTML = '<div class="note-container"></div>';
    await wait();
    fixture.firstElementChild.innerHTML = '<h2 id="detail-title">延迟挂载的标题</h2><div id="detail-desc">延迟挂载的正文</div>';
    await wait();
    check("先有空壳、稍后插入正文也能识别", panelText().includes("延迟挂载的标题"));
    fixture.innerHTML = note("64a111111111111111111111", "第一篇笔记");
    await wait();
    check("动态打开笔记：读取标题、正文和作者", panelText().includes("第一篇笔记") && panelText().includes("当前笔记的正文") && panelText().includes("作者小林"));
    document.querySelector("#vs-refresh").click();
    await wait();
    check("内容未变时手动重读正常完成", !panelText().includes("正在重新读取") && panelText().includes("第一篇笔记"));
    const panelScrollReads = runtime.stats.reads;
    document.querySelector("#vs-description").dispatchEvent(new Event("scroll"));
    await wait();
    check("滚动面板自身不触发页面重读", runtime.stats.reads === panelScrollReads);
    fixture.insertAdjacentHTML("beforeend", note("64a222222222222222222222", "隐藏预加载笔记", "offscreen"));
    await wait();
    check("预加载的屏幕外笔记不能抢走当前内容", panelText().includes("第一篇笔记") && !panelText().includes("隐藏预加载笔记"));
    fixture.querySelector("#detail-title").firstChild.data = "第一篇笔记已补全";
    await wait();
    check("正文区域异步文本更新会同步", panelText().includes("第一篇笔记已补全"));
    fixture.innerHTML = note("64a333333333333333333333", "第二篇笔记");
    await wait();
    check("替换笔记根节点后重新绑定并清除旧内容", panelText().includes("第二篇笔记") && !panelText().includes("第一篇笔记"));
    fixture.style.display = "none";
    await wait();
    check("关闭父容器：清除上篇内容", !panelText().includes("第二篇笔记"));
    fixture.style.display = "block";
    await wait();
    check("恢复父容器后自动重新识别", panelText().includes("第二篇笔记"));
    fixture.style.visibility = "hidden";
    await wait();
    check("仅 CSS visibility 隐藏时清空", !panelText().includes("第二篇笔记"));
    fixture.style.visibility = "visible";
    await wait();
    check("仅 CSS visibility 恢复时重新读取", panelText().includes("第二篇笔记"));
    fixture.style.opacity = "0";
    await wait();
    fixture.style.opacity = "1";
    await wait();
    check("仅透明度恢复也会重新识别", panelText().includes("第二篇笔记"));
    const beforeNoise = runtime.stats.reads;
    for (let i = 0; i < 200; i++) {
      const node = document.createElement("span"); node.textContent = `无关导航 ${i}`;
      document.querySelector("#noise").append(node);
    }
    await wait(650);
    check("200 次无关区域插入不触发内容重读", runtime.stats.reads === beforeNoise);
    const readsBeforeIdle = runtime.stats.reads;
    await wait(1800);
    check("空闲超过旧版轮询周期无重读或自身反馈循环", runtime.stats.reads === readsBeforeIdle);
    fixture.innerHTML = "";
    await wait();
    check("移除笔记后不残留旧内容", !panelText().includes("第二篇笔记"));
    runtime.destroy();
    fixture.innerHTML = video("7000000000000000001", "视频一文案") + video("7000000000000000002", "视频二文案", "offscreen");
    runtime = app.start(app.adapters.douyin);
    await wait();
    check("抖音读取可见视频，忽略预加载视频", panelText().includes("视频一文案") && !panelText().includes("视频二文案") && panelText().includes("视频作者"));
    const items = fixture.querySelectorAll('[data-e2e="feed-item"]');
    items[0].classList.add("offscreen"); items[1].classList.remove("offscreen");
    document.dispatchEvent(new Event("scroll"));
    await wait();
    check("网址不变切换视频也会更新", panelText().includes("视频二文案") && !panelText().includes("视频一文案"));
    items[1].querySelector('[data-e2e="video-desc"]').textContent = "稍后补全的视频文案";
    await wait();
    check("视频文案异步补全", panelText().includes("稍后补全的视频文案"));
    items[1].classList.add("swiper-slide-active");
    const counter = document.createElement("span");
    counter.className = "playback-time";
    items[1].append(counter);
    await wait();
    const beforeProgress = runtime.stats.reads;
    for (let i = 0; i < 30; i++) counter.textContent = String(i);
    await wait();
    check("当前视频的播放计时变化不触发文案重读", runtime.stats.reads === beforeProgress);
    const renders = runtime.stats.renders;
    document.dispatchEvent(new Event("scroll"));
    await wait();
    check("同一内容重复事件不会重复渲染", runtime.stats.renders === renders);
    items[1].querySelector('[data-e2e="video-desc"]').textContent = '<img src=x onerror="window.VOSS_XSS=true">';
    await wait();
    check("页面文字按纯文本显示，不能注入 HTML", !document.querySelector('#voss-scroll-panel img') && !window.VOSS_XSS);
    document.querySelector("#vs-collapse").click();
    check("原版折叠功能保留", getComputedStyle(document.querySelector("#voss-scroll-panel .vs-body")).display === "none");
    document.querySelector("#vs-collapse").click();
    check("旧模式按钮已移除；离线页面显示未连接模型说明", document.querySelectorAll('#voss-scroll-panel [data-mode]').length === 0 && panelText().includes("未连接模型"));
    const old = runtime;
    runtime = app.start(app.adapters.douyin);
    await wait();
    check("重复启动只保留一个面板", document.querySelectorAll("#voss-scroll-panel").length === 1);
    const oldReads = old.stats.reads;
    fixture.querySelectorAll('[data-e2e="video-desc"]')[1].textContent = "最终示例 · 你刷，我跟上";
    await wait();
    check("旧监听器已清理，只有新实例更新", old.stats.reads === oldReads && panelText().includes("最终示例"));
    runtime.destroy();
    fixture.innerHTML = video("7000000000000000003", "普通候选") + '<div data-e2e="feed-active-video" data-video-id="7000000000000000004" style="position:absolute;inset:0;padding:12px"><div><video></video><div data-e2e="video-desc">嵌套当前视频</div></div></div>';
    runtime = app.start(app.adapters.douyin);
    await wait();
    check("嵌套文案容器保留外层当前视频标识", panelText().includes("嵌套当前视频") && document.querySelector("#vs-source").href.endsWith("7000000000000000004"));
    fixture.innerHTML = '<div data-e2e="feed-item"><video></video><div data-e2e="video-desc">推荐页标签识别 <a href="https://www.douyin.com/search/topic?aweme_id=7000000000000000005">#创作</a></div></div>';
    await wait();
    check("推荐页从当前文案标签识别视频原链接", document.querySelector("#vs-source").href.endsWith("7000000000000000005"));
    check("最终没有旧版定时轮询函数", !String(app.start).includes("setInterval"));
    document.title = `Voss 测试：${passed} PASS / ${failed} FAIL`;
    document.body.dataset.testResult = failed ? "fail" : "pass";
  } catch (error) {
    failed++;
    log.push(`ERROR ${error.stack}`);
    results.textContent = `${passed} passed · ${failed} failed\n${log.join("\n")}`;
    document.title = "Voss 测试 ERROR";
  }
})();
